# The URL the site will be built for
base_url = "https://jerryidk.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "after-dark"


[markdown]
highlight_code = false


[extra]
# Put all your custom variables here
license = "none" # blog license
author = "Jerry"
